export const FETCH_LAWSUITS_SUCCESS = 'FETCH_LAWSUITS_SUCCESS';
export const FETCH_LAWSUITS_FAILURE = 'FETCH_LAWSUITS_FAILURE';
export const FETCH_LAWSUITS_REQUEST = 'FETCH_LAWSUITS_REQUEST';
export const RESET_LAWSUITS = 'RESET_LAWSUITS';

export const COI_SEARCH_SUCCESS = 'COI_SEARCH_SUCCESS';
export const COI_SEARCH_FAILURE = 'COI_SEARCH_FAILURE';
