export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const TOGGLE_EDIT = 'TOGGLE_EDIT';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
