export const FETCH_COUNTERPARTS_SUCCESS = 'FETCH_COUNTERPARTS_SUCCESS';
export const COUNTERPARTS_FAILURE = 'COUNTERPARTS_FAILURE';
export const ADD_COUNTERPART_TO_LAWSUIT = 'ADD_COUNTERPART_TO_LAWSUIT';
