export const FETCH_COUNTERPARTS_SUCCESS = 'FETCH_COUNTERPARTS_SUCCESS';
export const COUNTERPARTS_FAILURE = 'COUNTERPARTS_FAILURE';
export const ADD_COUNTERPART_TO_LAWSUIT_SUCCESS = 'ADD_COUNTERPART_TO_LAWSUIT_SUCCESS';
export const COUNTERPARTS_REQUEST = 'COUNTERPARTS_REQUEST';
export const DELETE_COUNTERPART_FROM_LAWSUIT_SUCCESS = 'DELETE_COUNTERPART_FROM_LAWSUIT_SUCCESS';
export const TOGGLE_EDIT_COUNTERPART = 'TOGGLE_EDIT_COUNTERPART';
export const UPDATE_COUNTERPART_SUCCESS = 'UPDATE_COUNTERPART_SUCCESS';
export const DELETE_COUNTERPART = 'DELETE_COUNTERPART';
